import torch
import torch.nn as nn
import torch.nn.functional as F
import math
import sys
import demucs.pretrained
from onnxruntime.quantization import quantize_dynamic, QuantType

# --- 1. Total Real-Mode Global Patches ---
torch.REAL_MODE = True

original_pad = F.pad
def custom_pad(input, pad, mode='constant', value=0.0):
    # Intercept padding on fake complex tensors generated by our patches
    if getattr(torch, 'REAL_MODE', False) and input.shape[-1] == 2 and input.dim() >= 3:
        if len(pad) > 0:
            # pad is originally meant for [..., F, T].
            # input is now [..., F, T, 2]. We must pad the '2' dimension with (0, 0).
            new_pad = (0, 0) + tuple(pad)
            return original_pad(input, new_pad, mode, value)
    return original_pad(input, pad, mode, value)

F.pad = custom_pad
torch.nn.functional.pad = custom_pad

# Defeat complex operations entirely across the tensor methods
torch.Tensor.view_as_complex = lambda self: self
torch.Tensor.view_as_real = lambda self: self
torch.view_as_real = lambda self: self
torch.is_complex = lambda self: False

# --- 2. Convolutional STFT/ISTFT Core Logic ---

class ConvSTFT(nn.Module):
    def __init__(self, n_fft, hop_length, center=True, normalized=True):
        super().__init__()
        self.n_fft = n_fft
        self.hop_length = hop_length
        self.center = center
        
        window_t = torch.hann_window(n_fft)
        
        basis_real = torch.zeros((n_fft // 2 + 1, n_fft))
        basis_imag = torch.zeros((n_fft // 2 + 1, n_fft))
        for k in range(n_fft // 2 + 1):
            for n in range(n_fft):
                angle = 2 * math.pi * k * n / n_fft
                basis_real[k, n] = math.cos(angle)
                basis_imag[k, n] = -math.sin(angle)
        
        basis_real *= window_t
        basis_imag *= window_t
        
        if normalized:
            basis_real /= math.sqrt(n_fft)
            basis_imag /= math.sqrt(n_fft)
            
        weights = torch.stack([basis_real, basis_imag], dim=1).view(-1, 1, n_fft)
        self.register_buffer('weight', weights)

    def forward(self, x):
        B, C, T = x.shape
        if self.center:
            # We use original_pad to bypass our custom_pad interceptor
            x = original_pad(x, (self.n_fft // 2, self.n_fft // 2), mode='reflect')
        
        x = x.reshape(B * C, 1, -1)
        out = F.conv1d(x, self.weight, stride=self.hop_length)
        
        T_prime = out.shape[-1]
        out = out.view(B, C, self.n_fft // 2 + 1, 2, T_prime)
        return out.permute(0, 1, 2, 4, 3)

class ConvISTFT(nn.Module):
    def __init__(self, n_fft, hop_length, center=True, normalized=True):
        super().__init__()
        self.n_fft = n_fft
        self.hop_length = hop_length
        self.center = center
        
        window_t = torch.hann_window(n_fft)
        
        basis_real = torch.zeros((n_fft // 2 + 1, n_fft))
        basis_imag = torch.zeros((n_fft // 2 + 1, n_fft))
        for k in range(n_fft // 2 + 1):
            for n in range(n_fft):
                angle = 2 * math.pi * k * n / n_fft
                basis_real[k, n] = math.cos(angle)
                basis_imag[k, n] = -math.sin(angle)
        
        basis_real *= window_t
        basis_imag *= window_t
        
        if normalized:
            basis_real /= math.sqrt(n_fft)
            basis_imag /= math.sqrt(n_fft)
        else:
            basis_real /= n_fft
            basis_imag /= n_fft
            
        weights = torch.stack([basis_real, basis_imag], dim=1).view(-1, 1, n_fft)
        self.register_buffer('weight', weights)

    def forward(self, x):
        B, C, F_dim, T, RI = x.shape
        x = x.permute(0, 1, 2, 4, 3).reshape(B * C, F_dim * 2, T)
        
        out = F.conv_transpose1d(x, self.weight, stride=self.hop_length)
        
        # Exact mathematical division for Hann window NOLA with hop=N/4
        out = out / 1.5
        
        out = out.view(B, C, -1)
        if self.center:
            out = out[..., self.n_fft // 2 : -self.n_fft // 2]
        return out

# --- 3. Custom spectro/ispectro wrappers ---

def custom_spectro(x, n_fft=512, hop_length=None, pad=0):
    if hop_length is None:
        hop_length = n_fft // 4
    
    *other, length = x.shape
    x = x.reshape(-1, length)
    
    stft = ConvSTFT(n_fft, hop_length, center=True, normalized=True).to(x.device)
    z = stft(x.unsqueeze(1))
    z = z.squeeze(1)
    
    _, freqs, frame, _ = z.shape
    z = z.view(*other, freqs, frame, 2)
    return z

def custom_ispectro(z, hop_length=None, length=None, pad=0, window=None):
    *other, freqs, frames, _ = z.shape
    n_fft = 2 * freqs - 2
    if hop_length is None:
        hop_length = n_fft // 4
        
    z = z.view(-1, freqs, frames, 2)
    
    istft = ConvISTFT(n_fft, hop_length, center=True, normalized=True).to(z.device)
    x = istft(z.unsqueeze(1))
    x = x.squeeze(1)
    
    if length is not None:
        x = x[..., :length]
        
    return x.view(*other, -1)

# --- 4. Main Execution ---

def main():
    print("Loading htdemucs...")
    model = demucs.pretrained.get_model('htdemucs')
    model.eval()

    print("Applying Perfect Real-Mode Patch across all sys.modules...")
    # Because demucs modules might have already imported `spectro` via `from .spec import spectro`
    # We MUST scan `sys.modules` to ensure every reference points to our custom functions.
    for mod_name, mod in sys.modules.items():
        if mod_name.startswith('demucs'):
            if hasattr(mod, 'spectro'):
                setattr(mod, 'spectro', custom_spectro)
            if hasattr(mod, 'ispectro'):
                setattr(mod, 'ispectro', custom_ispectro)

    print("Creating dummy input [1, 2, 441000]...")
    dummy_input = torch.randn(1, 2, 441000)

    print("Exporting to ONNX: htdemucs_base.onnx (opset 11)...")
    torch.onnx.export(
        model,
        dummy_input,
        "htdemucs_base.onnx",
        export_params=True,
        opset_version=11,
        do_constant_folding=True,
        input_names=['input'],
        output_names=['output'],
        dynamic_axes={
            'input': {2: 'audio_length'},
            'output': {2: 'audio_length'}
        }
    )

    print("Quantizing to INT8: htdemucs_quantized.onnx...")
    quantize_dynamic(
        "htdemucs_base.onnx",
        "htdemucs_quantized.onnx",
        weight_type=QuantType.QInt8
    )

    print("Export and quantization complete.")

if __name__ == "__main__":
    main()
